package com.abdownloadmanager.shared.ui.theme

import androidx.compose.ui.graphics.Color
import com.abdownloadmanager.shared.util.ui.MyColors

object DefaultThemes {

    // Default
    val default = ThemePack(
        id = "default",
        name = "Default",
        dark = MyColors(
            id = "default_dark",
            name = "Default Dark",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF60A6D9),
            onPrimary = Color(0xFFEFF2F6),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFFD1A6FF),
            onSecondary = Color(0xFFEFF2F6),
            background = Color(0xFF1E1F22),
            onBackground = Color(0xFFD6D6D6),
            surface = Color(0xFF2A2B2F),
            onSurface = Color(0xFFE0E0E0),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFEFEFEF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFE5E5E5),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF1E1E1E),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF1E1E1E),
            isLight = false,
        ),
        light = MyColors(
            id = "default_light",
            name = "Default Light",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF3576A1),
            onPrimary = Color(0xFFFFFFFF),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFF9700FF),
            onSecondary = Color(0xFFFFFFFF),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF232323),
            surface = Color(0xFFF2F2F2),
            onSurface = Color(0xFF232323),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFFFFFFF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFFFFFFF),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF232323),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF232323),
            isLight = true,
        ),
    )

    // Obsidian
    val obsidian = ThemePack(
        id = "obsidian",
        name = "Obsidian",
        dark = MyColors(
            id = "obsidian_dark",
            name = "Obsidian Dark",
            primary = Color(0xFF4791BF),
            onPrimary = Color.White,
            secondary = Color(0xFFB85DFF),
            onSecondary = Color.White,
            background = Color(0xFF16161E),
            onBackground = Color(0xFFBBBBBB),
            onSurface = Color(0xFFBBBBBB),
            surface = Color(0xFF22222A),
            error = Color(0xFFFF5757),
            onError = Color.White,
            success = Color(0xFF69BA5A),
            onSuccess = Color.White,
            warning = Color(0xFFFFBE56),
            onWarning = Color.White,
            info = Color(0xFF2F77D4),
            onInfo = Color.White,
            isLight = false,
        ),
        light = MyColors(
            id = "obsidian_light",
            name = "Obsidian Light",
            primary = Color(0xFF4791BF),
            onPrimary = Color.White,
            secondary = Color(0xFFB85DFF),
            onSecondary = Color.White,
            background = Color(0xFFF5F5FA),
            onBackground = Color(0xFF2A2A35),
            surface = Color(0xFFEAEAF0),
            onSurface = Color(0xFF2A2A35),
            error = Color(0xFFD32F2F),
            onError = Color.White,
            success = Color(0xFF388E3C),
            onSuccess = Color.White,
            warning = Color(0xFFE6A020),
            onWarning = Color(0xFF2A2A35),
            info = Color(0xFF1565C0),
            onInfo = Color.White,
            isLight = true,
        ),
    )

    // Deep Ocean
    val deepOcean = ThemePack(
        id = "deep_ocean",
        name = "Deep Ocean",
        dark = MyColors(
            id = "deep_ocean_dark",
            name = "Deep Ocean Dark",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF60A6D9),
            onPrimary = Color(0xFFEFF2F6),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFFD1A6FF),
            onSecondary = Color(0xFFEFF2F6),
            background = Color(0xFF17212B),
            onBackground = Color(0xFFE5EAF2),
            surface = Color(0xFF242F3D),
            onSurface = Color(0xFFE5EAF2),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFE5E5E5),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFE5E5E5),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF232323),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF232323),
            isLight = false,
        ),
        light = MyColors(
            id = "deep_ocean_light",
            name = "Deep Ocean Light",
            primary = Color(0xFF3A7CA5),
            primaryVariant = Color(0xFF5698C0),
            onPrimary = Color(0xFFFFFFFF),
            secondary = Color(0xFF7E57C2),
            secondaryVariant = Color(0xFFB39DDB),
            onSecondary = Color(0xFFFFFFFF),
            background = Color(0xFFF0F4F8),
            onBackground = Color(0xFF1A2530),
            surface = Color(0xFFE1E8EF),
            onSurface = Color(0xFF1A2530),
            error = Color(0xFFD32F2F),
            onError = Color(0xFFFFFFFF),
            success = Color(0xFF2E7D32),
            onSuccess = Color(0xFFFFFFFF),
            warning = Color(0xFFE6A020),
            onWarning = Color(0xFF1A2530),
            info = Color(0xFF2196F3),
            onInfo = Color(0xFFFFFFFF),
            isLight = true,
        ),
    )

    // Twilight
    val twilight = ThemePack(
        id = "twilight",
        name = "Twilight",
        dark = MyColors(
            id = "twilight_dark",
            name = "Twilight Dark",
            primary = Color(0xFF4791BF),
            onPrimary = Color.White,
            secondary = Color(0xFFB85DFF),
            onSecondary = Color.White,
            background = Color(0xFF13111C),
            onBackground = Color(0xFFE5DEFF),
            surface = Color(0xFF1E1B29),
            onSurface = Color(0xFFD4CBE5),
            error = Color(0xFFFF5E7E),
            onError = Color(0xFF410002),
            success = Color(0xFF00D289),
            onSuccess = Color(0xFF003320),
            warning = Color(0xFFFFB74D),
            onWarning = Color(0xFF4D2A00),
            info = Color(0xFF29B6F6),
            onInfo = Color(0xFF00334D),
            isLight = false,
        ),
        light = MyColors(
            id = "twilight_light",
            name = "Twilight Light",
            primary = Color(0xFF5C6BC0),
            onPrimary = Color.White,
            secondary = Color(0xFF9C27B0),
            onSecondary = Color.White,
            background = Color(0xFFF5F3FB),
            onBackground = Color(0xFF1A1528),
            surface = Color(0xFFEDE8F5),
            onSurface = Color(0xFF1A1528),
            error = Color(0xFFC62828),
            onError = Color.White,
            success = Color(0xFF00897B),
            onSuccess = Color.White,
            warning = Color(0xFFE65100),
            onWarning = Color.White,
            info = Color(0xFF0288D1),
            onInfo = Color.White,
            isLight = true,
        ),
    )

    // Black (AMOLED)
    val black = ThemePack(
        id = "black",
        name = "Black",
        dark = MyColors(
            id = "black_dark",
            name = "Black Dark",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF60A6D9),
            onPrimary = Color(0xFFEFF2F6),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFFD1A6FF),
            onSecondary = Color(0xFFEFF2F6),
            background = Color(0xFF000000),
            onBackground = Color(0xFFEFEFEF),
            surface = Color(0xFF1A1F26),
            onSurface = Color(0xFFEFEFEF),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFFFFFFF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFFFFFFF),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF000000),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF000000),
            isLight = false,
        ),
        light = MyColors(
            id = "black_light",
            name = "Black Light",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF3576A1),
            onPrimary = Color(0xFFFFFFFF),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFF9700FF),
            onSecondary = Color(0xFFFFFFFF),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF121212),
            surface = Color(0xFFF0F0F0),
            onSurface = Color(0xFF121212),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFFFFFFF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFFFFFFF),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF121212),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF121212),
            isLight = true,
        ),
    )

    // Gray
    val gray = ThemePack(
        id = "gray",
        name = "Gray",
        dark = MyColors(
            id = "gray_dark",
            name = "Gray Dark",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF60A6D9),
            onPrimary = Color(0xFFEFF2F6),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFFD1A6FF),
            onSecondary = Color(0xFFEFF2F6),
            background = Color(0xFF2C2C2C),
            onBackground = Color(0xFFD6D6D6),
            surface = Color(0xFF3A3A3A),
            onSurface = Color(0xFFE0E0E0),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFEFEFEF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFE5E5E5),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF1E1E1E),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF1E1E1E),
            isLight = false,
        ),
        light = MyColors(
            id = "gray_light",
            name = "Gray Light",
            primary = Color(0xFF4791BF),
            primaryVariant = Color(0xFF60A6D9),
            onPrimary = Color(0xFF20303A),
            secondary = Color(0xFFB85DFF),
            secondaryVariant = Color(0xFFD1A6FF),
            onSecondary = Color(0xFF20303A),
            background = Color(0xFFF0F0F0),
            onBackground = Color(0xFF232323),
            surface = Color(0xFFE0E0E0),
            onSurface = Color(0xFF232323),
            error = Color(0xFFEA4C3C),
            onError = Color(0xFFFFFFFF),
            success = Color(0xFF45B36B),
            onSuccess = Color(0xFFFFFFFF),
            warning = Color(0xFFF6C244),
            onWarning = Color(0xFF232323),
            info = Color(0xFF40A9F3),
            onInfo = Color(0xFF232323),
            isLight = true,
        ),
    )

    private val builtInPacks = listOf(
        default,
        obsidian,
        deepOcean,
        twilight,
        black,
        gray,
    )

    fun getAllPacks(): List<ThemePack> = builtInPacks

    fun getDefaultPack() = default
}
