/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abdownloadmanager.desktop

import com.abdownloadmanager.UpdateManager
import com.abdownloadmanager.desktop.di.Di
import com.abdownloadmanager.desktop.repository.AppRepository
import com.abdownloadmanager.desktop.ui.Ui
import com.abdownloadmanager.desktop.utils.*
import com.abdownloadmanager.desktop.utils.native_messaging.host.NativeMessagingHostLauncher
import com.abdownloadmanager.desktop.utils.renderapi.CustomRenderApi
import com.abdownloadmanager.desktop.utils.singleInstance.AnotherInstanceIsRunning
import com.abdownloadmanager.desktop.utils.singleInstance.EnsureAppIsAwake
import com.abdownloadmanager.desktop.utils.singleInstance.SingleInstanceManager
import com.abdownloadmanager.desktop.utils.singleInstance.SingleInstanceServerInitializer
import com.abdownloadmanager.desktop.utils.singleInstance.StartIfNotStartedCommand
import com.abdownloadmanager.integration.Integration
import com.abdownloadmanager.shared.util.DownloadSystem
import com.abdownloadmanager.shared.util.appinfo.PreviousVersion
import com.abdownloadmanager.shared.util.keepawake.KeepAwakeManager
import dev.nucleusframework.aot.runtime.AotRuntime
import ir.amirab.util.logger.AppLogger
import ir.amirab.util.logger.appLogger
import ir.amirab.util.writeText
import kotlinx.coroutines.runBlocking
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import kotlin.concurrent.thread
import kotlin.system.exitProcess

class App : AutoCloseable,
    KoinComponent {
    private val downloadSystem: DownloadSystem by inject()
    private val appRepository: AppRepository by inject()
    private val integration: Integration by inject()
    private val previousVersion: PreviousVersion by inject()
    private val updateManager: UpdateManager by inject()
    private val keepAwakeManager: KeepAwakeManager by inject()
    private val customRenderApi: CustomRenderApi by inject()

    //TODO Setup Native Messaging Feature
    //private val browserNativeMessaging: NativeMessaging by inject()
    fun start(
        appArguments: AppArguments,
        globalAppExceptionHandler: GlobalAppExceptionHandler,
    ) {
        try {
            runBlocking {
                //make sure to not get any dependency until boot the DI Container
                Di.boot()
                // it's better to organize these list of boot functions in a separate class

                // boot configs from the storage so download manager can use them on boot!
                customRenderApi.boot()
                appRepository.boot()
                integration.boot()
                downloadSystem.boot()
                previousVersion.boot()
                keepAwakeManager.boot()
                //TODO Setup Native Messaging Feature
                //waiting for compose kmp to add multi launcher to nativeDistributions,the PR is already exists but not merger
                //or maybe I should use a custom solution
                //browserNativeMessaging.boot()
                SingleInstanceServerInitializer.boot()
                Ui.boot(appArguments, globalAppExceptionHandler)
            }
        } catch (e: Exception) {
            globalAppExceptionHandler.onProcessIsUseless()
            throw e
        }
    }

    override fun close() {
        //nothing yet!
    }
}


fun main(args: Array<String>) {
    try {
        AppArguments.init(args)
        AppProperties.boot()
        val appArguments = AppArguments.get()
        AppLogger.init(
            writeToConsole = false,
            logFilePath = AppInfo.definedPaths.logDir.takeIf {
                AppInfo.isInDebugMode()
            },
        )

        // Native messaging mode - handle early before any UI initialization
        if (appArguments.nativeMessaging) {
            runNativeMessagingMode(args)
        }

        if (appArguments.version) {
            dispatchVersionAndExit()
        }
        if (appArguments.exit) {
            exitExistingProcessAndExit()
        }
        if (appArguments.startIfNotStarted && !AppInfo.isInIDE()) {
            runBlocking {
                StartIfNotStartedCommand.startAndWaitForRunIfNotRunning()
            }
        }
        if (appArguments.getIntegrationPort) {
            runBlocking {
                dispatchIntegrationPortAndExit()
            }
        }
        trainTheAOT()
        //going to start main app
        defaultApp(
            appArguments = appArguments,
        )

    } catch (e: Throwable) {
        appLogger.e(throwable = e) { "Fail to start the ${AppInfo.displayName} app because:" }
        System.err.println("Fail to start the ${AppInfo.displayName} app because:")
        e.printStackTrace()
        AppInfo.definedPaths.crashLogFile.writeText(e.stackTraceToString())
        exitProcess(-1)
    }
}

private fun trainTheAOT(
) {
    if (!AotRuntime.isTraining()) {
        return
    }
    thread {
        Thread.sleep(30_000)
        exitProcess(0)
    }
}


private fun dispatchVersionAndExit(): Nothing {
    print(AppInfo.version)
    exitProcess(0)
}

private fun exitExistingProcessAndExit(): Nothing {
    val singleInstance = SingleInstanceManager.get()
    runBlocking {
        singleInstance.singleInstanceService().useService {
            it.exit()
        }
    }
    exitProcess(0)
}

private suspend fun dispatchIntegrationPortAndExit(): Nothing {
    val singleInstance = SingleInstanceManager.get()

    val port = runCatching {
        singleInstance.singleInstanceService().useService { it.getIntegrationPort() }
    }.getOrElse { IntegrationPortBroadcaster.INTEGRATION_UNKNOWN }

    print(port)
    exitProcess(0)
}


private fun defaultApp(
    appArguments: AppArguments,
) {
    val singleInstance = SingleInstanceManager.get()
    try {
        singleInstance.lockInstance()
    } catch (e: AnotherInstanceIsRunning) {
        println("instance already running")
        runBlocking {
            singleInstance.singleInstanceService().useService {
                it.showUserThatAppIsRunning()
            }
        }
        return
    }
    val startedMessage = "${AppInfo.displayName}-${AppInfo.version} started"
    appLogger.i { startedMessage }
    println(startedMessage)
    if (AppInfo.isInIDE()) {
        appLogger.i { "App is in IDE" }
    }

    val globalExceptionHandler = createAndSetGlobalExceptionHandler()
    App().use {
        it.start(
            appArguments = appArguments,
            globalAppExceptionHandler = globalExceptionHandler,
        )
    }
}

/**
 * Runs the app in native messaging mode for browser extension communication.
 * This mode runs without UI and communicates via stdin/stdout.
 */
private fun runNativeMessagingMode(args: Array<String>): Nothing {
    val nmArgs = args.drop(1).toTypedArray() // nativeMessaging command
    NativeMessagingHostLauncher.main(nmArgs)
    exitProcess(0)
}
