/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.abdownloadmanager.desktop

import com.abdownloadmanager.desktop.cli.Cli
import com.github.ajalt.clikt.command.main
import kotlinx.coroutines.runBlocking

/**
 * default launcher
 */

class DefaultAppLauncher {
    suspend fun main(args: Array<String>) {
        /**
         * @see com.abdownloadmanager.desktop.cli.gui.run.RunGui
         */
        Cli().main(arrayOf(AppArguments.Commands.GUI, AppArguments.Commands.RUN, *args))
    }
}

fun main(args: Array<String>) {
    runBlocking {
        DefaultAppLauncher().main(args)
    }
}
