name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: amir1376.ABDownloadManager
          token: ${{ secrets.WINGET_TOKEN }}
